<test>
<testsuite name="Mocha Tests" tests="31" failures="19" errors="19" skipped="0" timestamp="Thu, 20 Apr 2017 06:00:19 GMT" time="17.222">
<testcase classname="App API REST test" name="[POST] Login" time="0.193"/>
<testcase classname="App API REST test" name="[POST]  Get notifications" time="0.169"/>
<testcase classname="App API REST test" name="[POST]  Archive notification" time="0.13"/>
<testcase classname="App API REST test" name="[GET]  Archive all notifications" time="0.095"/>
<testcase classname="App API REST test" name="[GET]  List of devices" time="0.331"/>
<testcase classname="App API REST test" name="[POST]  Save token" time="0.116"/>
<testcase classname="App API REST test" name="[POST]  Tracking vehicle" time="0.266"/>
<testcase classname="App API REST test" name="[GET]  Tracking1 vehicle" time="0.097"/>
<testcase classname="App API REST test" name="[POST]  Set vehicle as default" time="0.093"/>
<testcase classname="App API REST test" name="[POST]  Config user-vehicle push enable" time="0"><failure>expected 202 to be 200
AssertionError: expected 202 to be 200
    at Assertion.fail (node_modules/should/cjs/should.js:258:17)
    at Assertion.value (node_modules/should/cjs/should.js:335:19)
    at Test.&lt;anonymous&gt; (test/test_app.js:199:26)
    at Test.assert (node_modules/supertest/lib/test.js:179:6)
    at assert (node_modules/supertest/lib/test.js:131:12)
    at node_modules/supertest/lib/test.js:128:5
    at Test.Request.callback (node_modules/superagent/lib/node/index.js:652:14)
    at node_modules/superagent/lib/node/index.js:866:18
    at IncomingMessage.&lt;anonymous&gt; (node_modules/superagent/lib/node/parsers/json.js:16:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)</failure></testcase>
<testcase classname="App API REST test" name="[POST]  Config user preferences" time="0.1"/>
<testcase classname="App API REST test" name="[POST]  Config user-vehicle config notifications" time="0"><failure>expected 202 to be 200
AssertionError: expected 202 to be 200
    at Assertion.fail (node_modules/should/cjs/should.js:258:17)
    at Assertion.value (node_modules/should/cjs/should.js:335:19)
    at Test.&lt;anonymous&gt; (test/test_app.js:238:26)
    at Test.assert (node_modules/supertest/lib/test.js:179:6)
    at assert (node_modules/supertest/lib/test.js:131:12)
    at node_modules/supertest/lib/test.js:128:5
    at Test.Request.callback (node_modules/superagent/lib/node/index.js:652:14)
    at node_modules/superagent/lib/node/index.js:866:18
    at IncomingMessage.&lt;anonymous&gt; (node_modules/superagent/lib/node/parsers/json.js:16:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)</failure></testcase>
<testcase classname="App API REST test" name="[GET]  Get status notifications" time="0.089"/>
<testcase classname="App API REST test" name="[GET]  Get graph data" time="0"><failure>expected 202 to be 200
AssertionError: expected 202 to be 200
    at Assertion.fail (node_modules/should/cjs/should.js:258:17)
    at Assertion.value (node_modules/should/cjs/should.js:335:19)
    at Test.&lt;anonymous&gt; (test/test_app.js:266:26)
    at Test.assert (node_modules/supertest/lib/test.js:179:6)
    at assert (node_modules/supertest/lib/test.js:131:12)
    at node_modules/supertest/lib/test.js:128:5
    at Test.Request.callback (node_modules/superagent/lib/node/index.js:652:14)
    at node_modules/superagent/lib/node/index.js:866:18
    at IncomingMessage.&lt;anonymous&gt; (node_modules/superagent/lib/node/parsers/json.js:16:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)</failure></testcase>
<testcase classname="App API REST test" name="[GET]  Get report daily data" time="0"><failure>expected 202 to be 200
AssertionError: expected 202 to be 200
    at Assertion.fail (node_modules/should/cjs/should.js:258:17)
    at Assertion.value (node_modules/should/cjs/should.js:335:19)
    at Test.&lt;anonymous&gt; (test/test_app.js:280:26)
    at Test.assert (node_modules/supertest/lib/test.js:179:6)
    at assert (node_modules/supertest/lib/test.js:131:12)
    at node_modules/supertest/lib/test.js:128:5
    at Test.Request.callback (node_modules/superagent/lib/node/index.js:652:14)
    at node_modules/superagent/lib/node/index.js:866:18
    at IncomingMessage.&lt;anonymous&gt; (node_modules/superagent/lib/node/parsers/json.js:16:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)</failure></testcase>
<testcase classname="App API REST test" name="[GET]  Resert graph data" time="0"><failure>expected 202 to be 200
AssertionError: expected 202 to be 200
    at Assertion.fail (node_modules/should/cjs/should.js:258:17)
    at Assertion.value (node_modules/should/cjs/should.js:335:19)
    at Test.&lt;anonymous&gt; (test/test_app.js:294:26)
    at Test.assert (node_modules/supertest/lib/test.js:179:6)
    at assert (node_modules/supertest/lib/test.js:131:12)
    at node_modules/supertest/lib/test.js:128:5
    at Test.Request.callback (node_modules/superagent/lib/node/index.js:652:14)
    at node_modules/superagent/lib/node/index.js:866:18
    at IncomingMessage.&lt;anonymous&gt; (node_modules/superagent/lib/node/parsers/json.js:16:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)</failure></testcase>
<testcase classname="App API REST test" name="[POST]  Check area" time="0"><failure>expected 502 to be 200
AssertionError: expected 502 to be 200
    at Assertion.fail (node_modules/should/cjs/should.js:258:17)
    at Assertion.value (node_modules/should/cjs/should.js:335:19)
    at Test.&lt;anonymous&gt; (test/test_app.js:319:26)
    at Test.assert (node_modules/supertest/lib/test.js:179:6)
    at assert (node_modules/supertest/lib/test.js:131:12)
    at node_modules/supertest/lib/test.js:128:5
    at Test.Request.callback (node_modules/superagent/lib/node/index.js:672:3)
    at IncomingMessage.&lt;anonymous&gt; (node_modules/superagent/lib/node/index.js:866:18)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)</failure></testcase>
<testcase classname="Area API REST test" name="[POST]    Get all areas" time="2.003"><failure>Timeout of 2000ms exceeded. For async tests and hooks, ensure &quot;done()&quot; is called; if returning a Promise, ensure it resolves.
Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure &quot;done()&quot; is called; if returning a Promise, ensure it resolves.</failure></testcase>
<testcase classname="Area API REST test" name="[GET]    Get area" time="0"><failure>socket hang up
Error: socket hang up
    at createHangUpError (_http_client.js:253:15)
    at TLSSocket.socketOnEnd (_http_client.js:345:23)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)</failure></testcase>
<testcase classname="Fleet API REST test" name="[POST]    Get all fleets" time="2.003"><failure>Timeout of 2000ms exceeded. For async tests and hooks, ensure &quot;done()&quot; is called; if returning a Promise, ensure it resolves.
Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure &quot;done()&quot; is called; if returning a Promise, ensure it resolves.</failure></testcase>
<testcase classname="Fleet API REST test" name="[GET]    Get fleet" time="0"><failure>socket hang up
Error: socket hang up
    at createHangUpError (_http_client.js:253:15)
    at TLSSocket.socketOnEnd (_http_client.js:345:23)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)</failure></testcase>
<testcase classname="Login API REST test" name="[POST]    Login" time="2.003"><failure>Timeout of 2000ms exceeded. For async tests and hooks, ensure &quot;done()&quot; is called; if returning a Promise, ensure it resolves.
Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure &quot;done()&quot; is called; if returning a Promise, ensure it resolves.</failure></testcase>
<testcase classname="Login API REST test" name="[POST]    Validate" time="0.164"/>
<testcase classname="Tracking API REST test" name="[GET]    Get tracking1 from 1 fleet" time="0"><failure>expected 502 to be 200
AssertionError: expected 502 to be 200
    at Assertion.fail (node_modules/should/cjs/should.js:258:17)
    at Assertion.value (node_modules/should/cjs/should.js:335:19)
    at Test.&lt;anonymous&gt; (test/test_tracking.js:26:32)
    at Test.assert (node_modules/supertest/lib/test.js:179:6)
    at assert (node_modules/supertest/lib/test.js:131:12)
    at node_modules/supertest/lib/test.js:128:5
    at Test.Request.callback (node_modules/superagent/lib/node/index.js:672:3)
    at IncomingMessage.&lt;anonymous&gt; (node_modules/superagent/lib/node/index.js:866:18)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)</failure></testcase>
<testcase classname="Tracking API REST test" name="[POST]    Get tracking1 from fleets" time="2.003"><failure>Timeout of 2000ms exceeded. For async tests and hooks, ensure &quot;done()&quot; is called; if returning a Promise, ensure it resolves.
Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure &quot;done()&quot; is called; if returning a Promise, ensure it resolves.</failure></testcase>
<testcase classname="Tracking API REST test" name="[GET]    Get tracking1 from 1 vehicle" time="0"><failure>expected 503 to be 200
AssertionError: expected 503 to be 200
    at Assertion.fail (node_modules/should/cjs/should.js:258:17)
    at Assertion.value (node_modules/should/cjs/should.js:335:19)
    at Test.&lt;anonymous&gt; (test/test_tracking.js:45:32)
    at Test.assert (node_modules/supertest/lib/test.js:179:6)
    at assert (node_modules/supertest/lib/test.js:131:12)
    at node_modules/supertest/lib/test.js:128:5
    at Test.Request.callback (node_modules/superagent/lib/node/index.js:672:3)
    at IncomingMessage.&lt;anonymous&gt; (node_modules/superagent/lib/node/index.js:866:18)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)</failure></testcase>
<testcase classname="Tracking API REST test" name="[POST]    Get tracking1 from vehicles" time="0"><failure>expected 502 to be 200
AssertionError: expected 502 to be 200
    at Assertion.fail (node_modules/should/cjs/should.js:258:17)
    at Assertion.value (node_modules/should/cjs/should.js:335:19)
    at Test.&lt;anonymous&gt; (test/test_tracking.js:60:32)
    at Test.assert (node_modules/supertest/lib/test.js:179:6)
    at assert (node_modules/supertest/lib/test.js:131:12)
    at node_modules/supertest/lib/test.js:128:5
    at Test.Request.callback (node_modules/superagent/lib/node/index.js:672:3)
    at IncomingMessage.&lt;anonymous&gt; (node_modules/superagent/lib/node/index.js:866:18)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)</failure></testcase>
<testcase classname="Tracking API REST test" name="[POST]    Get tracking1 from all vehicles" time="2.002"><failure>Timeout of 2000ms exceeded. For async tests and hooks, ensure &quot;done()&quot; is called; if returning a Promise, ensure it resolves.
Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure &quot;done()&quot; is called; if returning a Promise, ensure it resolves.</failure></testcase>
<testcase classname="Tracking API REST test" name="[POST]    Get tracking from vehicle" time="0"><failure>socket hang up
Error: socket hang up
    at createHangUpError (_http_client.js:253:15)
    at TLSSocket.socketOnEnd (_http_client.js:345:23)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)</failure></testcase>
<testcase classname="Vehicle API REST test" name="[POST]    Get all vehicles" time="2.003"><failure>Timeout of 2000ms exceeded. For async tests and hooks, ensure &quot;done()&quot; is called; if returning a Promise, ensure it resolves.
Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure &quot;done()&quot; is called; if returning a Promise, ensure it resolves.</failure></testcase>
<testcase classname="Vehicle API REST test" name="[GET]    Get vehicle" time="0"><failure>socket hang up
Error: socket hang up
    at createHangUpError (_http_client.js:253:15)
    at TLSSocket.socketOnEnd (_http_client.js:345:23)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)</failure></testcase>
</testsuite>
</test>
